### PR TITLE
Pre commit tweaks

### PR DESCRIPTION
**Pull request by harrisonpim**
drive-by PR with some tiny tweaks, while setting up the [targets-sprint-cop28](https://github.com/climatepolicyradar/targets-sprint-cop28) repo

- tidies up the dev dependency groups
- adds a poetry lock file check
- autoformats with ruff instead of black (including notebooks)

### CODE REVIEW

**Review by mpjuhasz — COMMENTED** [review]
LGTM -- any particular reason why we should be moving to ruff from black?

**Comment by harrisonpim** [comment]
there are a couple of reasons:
- [ruff's much faster than black](https://astral.sh/blog/the-ruff-formatter#:~:text=An%20obsessive%20focus%20on%20performance.%20Ruff%E2%80%99s%20formatter%20is%20over%2030x%20faster%20than%20Black%20and%20100x%20faster%20than%20YAPF%2C%20formatting%20large%20Python%20projects%20in%20milliseconds.%20Even%20with%20caching%20disabled%2C%20Ruff%E2%80%99s%20formatter%20is%20faster%20than%20Black%20with%20caching.%20It%27s%20really%20fast!)
- we were already running ruff
- their outputs should be [approximately identical](https://docs.astral.sh/ruff/formatter/#black-compatibility)!

all of those reasons are minor though, so i'm happy to be swayed back to black if people have stronger feelings!

**Comment by kdutia** [comment]
@harrisonpim do we need this in there too? https://docs.astral.sh/ruff/faq/#does-ruff-support-jupyter-notebooks

**Comment by harrisonpim** [comment]
[it's there already](https://github.com/climatepolicyradar/experiment-template/pull/12/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R15), but in a different way! i've verified that it works with both scripts and notebooks

**Review by kdutia — APPROVED** [review]

**Pull request merged**
